### PR TITLE
:bug: Correctly encode image paths for src attribute

### LINKED ISSUE #38: Images with % in their URI do not load
Let me begin by thanking you for the great editor! It's much better than any alternatives I've found.
I am using Atom 1.0.2 and Windows 8.1 x64.
When opening an image with `%` in its URI, it is not displayed properly, but can still be opened from the tree view. The dev tools report an `ERR_FILE_NOT_FOUND`.
image

Removing the `%`s seem to fix this issue.
image

### PR DESCRIPTION
**Pull request by Tyriar**
Images such as '?.png', '#.png' and '%2F.png' all fail loading due to not being
correctly encoded before passing off to the img src attribute. The fix for this
is to encode the URI using encodeURI and then manually encode '?' and '#' since
file paths cannot have a hash fragments or query string.

Fixes #38

### CODE REVIEW

**Comment by code-disaster** [comment]
FYI this seems to only replace the first occurrence. 'img#a#b.png' still does not work.

File: lib/image-editor.coffee [hunk 1]
```diff
@@ -52,7 +52,7 @@ class ImageEditor
   # Retrieves the URI of the image.
   #
   # Returns a {String}.
-  getURI: -> @getPath()
+  getURI: -> encodeURI(@getPath()).replace('#', '%23').replace('?', '%3F')
```
Comment (kevinsawicki) [inline lib/image-editor.coffee]: The file path could have multiple `#` and `?` in it and I believe this will only replace the first occurrence.

```js
'???###'.replace('#', '%23').replace('?', '%3F')
"%3F??%23##"
```

All the occurrences should be converted right?

Comment (Tyriar) [inline lib/image-editor.coffee]: Yes, @code-disaster has a pull out to fix this up https://github.com/Tyriar/image-view/pull/1

**Comment by Tyriar** [comment]
Think this is good to go, thanks @code-disaster

**Comment by kevinsawicki** [comment]
Awesome, thanks for this :ship:
