### PR TITLE
Close image view if file is deleted externally

### LINKED ISSUE #74: Errors thrown when image-view tab is open and image file is deleted.
1. Open an image in a Atom tab with image-view enabled.
2. Delete image file outside of Atom (i.e. shell, etc)
3. Click on image-view tab for deleted file
4.
```
Error: ENOENT: no such file or directory, stat '/Users/eric/Desktop/IMAGE.png'
    at Error (native)
    at fs.statSync (fs.js:897:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:263:16)
    at ImageEditorView.module.exports.ImageEditorView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/image-view/lib/image-editor-view.js:100:34)
    at ImageEditorView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:184:25)
    at ImageEditorView.ScrollView [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new ImageEditorView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/image-view/lib/image-editor-view.js:20:52)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.itemRemoved (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:180:37)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:574:20)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:643:16)
    at atom-tabs.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:325:26)
    at Object.addElementCommands.tabs:close-tab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:95:26)
    at atom-tabs.commandsWithPropagationStopped.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:86:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1133:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:354:25)
    at emitThree (events.js:110:13)
    at EventEmitter.emit (events.js:188:7)
```

When I tried to replicate this exactly, sometimes Atom closes the tab itself, but sometimes it remains open and image-view attempts to reload the image file without checking to see if it still exists. The error popup reappears when closed and it becomes impossible to close the tabs.

### PR DESCRIPTION
**Pull request by TimvdLippe**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Whenever an image was deleted externally, it threw an exception. Now, the pane is destroyed instead.

Note that I had to mimic the `get element()`, because destroying a panel item was actually retrieving the element again. E.g. `pane.destroyItem` asks for the element to be disposed. This is somewhat of a hack, but else I had to touch Atom core code to fix this loophole, if it could be fixed at all.

### Alternate Designs

You could add a placeholder message saying "Image has been deleted", but in #74 the proposed solution was to close the pane.

### Benefits

No more exceptions are thrown and a lot less issues opened on this repository :smile: 

### Possible Drawbacks

I don't know

### Applicable Issues

Fixes #74

### CODE REVIEW

File: lib/image-editor.js [hunk 1]
```diff
@@ -17,17 +17,26 @@ export default class ImageEditor {
 
   constructor (filePath) {
     this.file = new File(filePath)
+    this.file.onDidDelete(() => {
+      this.subscriptions.dispose()
+      const pane = atom.workspace.paneForURI(filePath)
+      pane.destroyItem(pane.itemForURI(filePath))
```
Comment (TimvdLippe) [inline lib/image-editor.js]: I am not sure what would happen if the `pane` is undefined here. Is the image editor view always up and thus the `paneForURI` always returns a pane?

Also should `this.file` be disposed on destroy? I have no good knowledge of the internal workings of the lifecycles, so please point out any issues if you aware of them :)

File: lib/image-editor.js [hunk 2]
```diff
@@ -17,17 +17,26 @@ export default class ImageEditor {
...
-    return this.view.element
+    return this.view && this.view.element || document.createElement('div')
   }
 
   get view () {
     if (!this.editorView) {
-      this.editorView = new ImageEditorView(this)
+      try {
+        this.editorView = new ImageEditorView(this)
+      } catch (e) {
```
Comment (TimvdLippe) [inline lib/image-editor.js]: Should `e` be logged somewhere? Is there any guideline for this?

Comment (BinaryMuse) [inline lib/image-editor.js]: What's the situation where constructing an `ImageEditorView` would throw an exception? Just if the file doesn't exist?

File: lib/image-editor.js (hunk 1 above)
Comment (BinaryMuse) [inline lib/image-editor.js]: > I am not sure what would happen if the `pane` is undefined here.

Hmm, I think perhaps it would be fine to wrap the destroy call in a `try`/`catch`.

> should `this.file` be disposed on destroy?

`this.file.onDidDelete` will return a `Disposable` instance that should be added to the `this.subscriptions` composite disposable so we don't continue watching the file after the editor is closed.

File: lib/image-editor.js (hunk 2 above)
Comment (TimvdLippe) [inline lib/image-editor.js]: So the `onDidDelete` destroys the pane, but that pane then tries to obtain the view and invokes the `get view`. Thus, in this situation, the `ImageEditorView` crashes with the reported error. I have added a comment to make this more clear.

**Comment by ungb** [comment]
Hey @TimvdLippe, 

Can you resolve the conflicts this has with master?  I'll take this for a spin and hopefully can get this merge soon!

**Comment by TimvdLippe** [comment]
Sadly I cant work on it for the coming months. Could you manually merge it? Thanks!

**Comment by BinaryMuse** [comment]
@ungb I've resolved the conflicts. Ready for testing!

**Comment by ungb** [comment]
looks good after testing!  merging!
